import _ from 'lodash';

const ActData = {
  Encounter: {
    n: '\n',
    t: '\t',
    title: 'Encounter',
    duration: '13:09',
    DURATION: '789',
    damage: '1840349',
    'damage-m': '1.84',
    'DAMAGE-k': '1840',
    'DAMAGE-m': '2',
    'DAMAGE-b': '0',
    dps: '2332.51',
    DPS: '2333',
    'DPS-k': '2',
    'DPS-m': 'DPS-m',
    encdps: '2332.51',
    ENCDPS: '2333',
    'ENCDPS-k': '2',
    'ENCDPS-m': '0',
    hits: '4942',
    crithits: '1206',
    'crithit%': '0%',
    misses: '11',
    hitfailed: '0',
    swings: '4953',
    tohit: '98.90',
    TOHIT: '99',
    maxhit: 'Limit Break-Final Heaven-34210',
    MAXHIT: 'Limit Break-34210',
    healed: '1810233',
    enchps: '2294.34',
    ENCHPS: '2294',
    'ENCHPS-k': '2',
    'ENCHPS-m': '0',
    critheals: '1206',
    'critheal%': '0%',
    heals: '2771',
    cures: '4',
    maxheal: 'White Mage One-Benediction-6974',
    MAXHEAL: 'White Mage One-6974',
    maxhealward: 'White Mage One-Benediction-6974',
    MAXHEALWARD: 'White Mage One-6974',
    damagetaken: '1052500',
    healstaken: '1812323',
    powerdrain: '0',
    powerheal: '18483',
    kills: '10',
    deaths: '4',
    CurrentZoneName: 'An instance',
    Last10DPS: '2095',
    Last30DPS: '1922',
    Last60DPS: '2347',
  },
  Combatant: {
    'Monk One': {
      n: '\n',
      t: '\t',
      name: 'YOU',
      duration: '12:56',
      DURATION: '776',
      damage: '355882',
      'damage-m': '0.36',
      'damage-b': '0.00',
      'DAMAGE-k': '356',
      'DAMAGE-m': '0',
      'DAMAGE-b': '0',
      'damage%': '19%',
      dps: '458.61',
      DPS: '459',
      'DPS-k': '0',
      'DPS-m': '0',
      encdps: '451.05',
      ENCDPS: '451',
      'ENCDPS-k': '0',
      'ENCDPS-m': '0',
      hits: '811',
      crithits: '200',
      'crithit%': '25%',
      crittypes: '-',
      misses: '2',
      hitfailed: '0',
      swings: '813',
      tohit: '99.75',
      TOHIT: '100',
      maxhit: 'True Strike-1392',
      MAXHIT: '1392',
      healed: '0',
      'healed%': '0%',
      enchps: '0.00',
      ENCHPS: '0',
      'ENCHPS-k': '0',
      'ENCHPS-m': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '0',
      cures: '0',
      maxheal: '',
      MAXHEAL: '',
      maxhealward: '',
      MAXHEALWARD: '',
      damagetaken: '100037',
      healstaken: '146767',
      powerdrain: '0',
      powerheal: '0',
      kills: '3',
      deaths: '1',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'YOU',
      NAME4: 'YOU',
      NAME5: 'YOU',
      NAME6: 'YOU',
      NAME7: 'YOU',
      NAME8: 'YOU',
      NAME9: 'YOU',
      NAME10: 'YOU',
      NAME11: 'YOU',
      NAME12: 'YOU',
      NAME13: 'YOU',
      NAME14: 'YOU',
      NAME15: 'YOU',
      Last10DPS: '0',
      Last30DPS: '95',
      Last60DPS: '292',
      Job: 'Mnk',
      ParryPct: '9%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Bard One': {
      n: '\n',
      t: '\t',
      name: 'Bard One',
      duration: '13:09',
      DURATION: '789',
      damage: '350064',
      'damage-m': '0.35',
      'DAMAGE-k': '350',
      'DAMAGE-m': '0',
      'damage%': '19%',
      dps: '443.68',
      DPS: '444',
      'DPS-k': '0',
      encdps: '443.68',
      ENCDPS: '444',
      'ENCDPS-k': '0',
      hits: '1240',
      crithits: '475',
      'crithit%': '38%',
      misses: '0',
      hitfailed: '0',
      swings: '1240',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: 'Heavy Shot-1016',
      MAXHIT: '1016',
      healed: '2798',
      'healed%': '0%',
      enchps: '3.55',
      ENCHPS: '4',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '3',
      cures: '0',
      maxheal: 'Second Wind-1005',
      MAXHEAL: '1005',
      maxhealward: 'Second Wind-1005',
      MAXHEALWARD: '1005',
      damagetaken: '77145',
      healstaken: '122216',
      powerdrain: '0',
      powerheal: '0',
      kills: '1',
      deaths: '1',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Bar',
      NAME4: 'Bard',
      NAME5: 'Bard',
      NAME6: 'Bard O',
      NAME7: 'Bard On',
      NAME8: 'Bard One',
      NAME9: 'Bard One',
      NAME10: 'Bard One',
      NAME11: 'Bard One',
      NAME12: 'Bard One',
      NAME13: 'Bard One',
      NAME14: 'Bard One',
      NAME15: 'Bard One',
      Last10DPS: '0',
      Last30DPS: '293',
      Last60DPS: '354',
      Job: 'Brd',
      ParryPct: '50%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '34%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Dragoon One': {
      n: '\n',
      t: '\t',
      name: 'Dragoon One',
      duration: '13:06',
      DURATION: '786',
      damage: '331961',
      'damage-m': '0.33',
      'DAMAGE-k': '332',
      'DAMAGE-m': '0',
      'damage%': '18%',
      dps: '422.34',
      DPS: '422',
      'DPS-k': '0',
      encdps: '420.74',
      ENCDPS: '421',
      'ENCDPS-k': '0',
      hits: '830',
      crithits: '141',
      'crithit%': '17%',
      misses: '1',
      hitfailed: '0',
      swings: '831',
      tohit: '99.88',
      TOHIT: '100',
      maxhit: 'Full Thrust-2488',
      MAXHIT: '2488',
      healed: '11656',
      'healed%': '0%',
      enchps: '14.77',
      ENCHPS: '15',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '26',
      cures: '0',
      maxheal: 'Second Wind-1108',
      MAXHEAL: '1108',
      maxhealward: 'Second Wind-1108',
      MAXHEALWARD: '1108',
      damagetaken: '90082',
      healstaken: '155129',
      powerdrain: '0',
      powerheal: '0',
      kills: '2',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Dra',
      NAME4: 'Drag',
      NAME5: 'Drago',
      NAME6: 'Dragoo',
      NAME7: 'Dragoon',
      NAME8: 'Dragoon',
      NAME9: 'Dragoon O',
      NAME10: 'Dragoon On',
      NAME11: 'Dragoon One',
      NAME12: 'Dragoon One',
      NAME13: 'Dragoon One',
      NAME14: 'Dragoon One',
      NAME15: 'Dragoon One',
      Last10DPS: '0',
      Last30DPS: '168',
      Last60DPS: '353',
      Job: 'Drg',
      ParryPct: '55%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'BlackMage One': {
      n: '\n',
      t: '\t',
      name: 'BlackMage One',
      duration: '13:06',
      DURATION: '786',
      damage: '329454',
      'damage-m': '0.33',
      'DAMAGE-k': '329',
      'DAMAGE-m': '0',
      'damage%': '17%',
      dps: '419.15',
      DPS: '419',
      'DPS-k': '0',
      encdps: '417.56',
      ENCDPS: '418',
      'ENCDPS-k': '0',
      hits: '405',
      crithits: '57',
      'crithit%': '14%',
      misses: '0',
      hitfailed: '0',
      swings: '405',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: 'Flare-3606',
      MAXHIT: '3606',
      healed: '0',
      'healed%': '0%',
      enchps: '0.00',
      ENCHPS: '0',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '0',
      cures: '0',
      maxheal: '',
      MAXHEAL: '',
      maxhealward: '',
      MAXHEALWARD: '',
      damagetaken: '87977',
      healstaken: '139709',
      powerdrain: '0',
      powerheal: '4820',
      kills: '0',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Bla',
      NAME4: 'Blac',
      NAME5: 'Black',
      NAME6: 'BlackM',
      NAME7: 'BlackMa',
      NAME8: 'BlackMag',
      NAME9: 'BlackMage',
      NAME10: 'BlackMage',
      NAME11: 'BlackMage O',
      NAME12: 'BlackMage On',
      NAME13: 'BlackMage One',
      NAME14: 'BlackMage One',
      NAME15: 'BlackMage One',
      Last10DPS: '0',
      Last30DPS: '206',
      Last60DPS: '293',
      Job: 'Blm',
      ParryPct: '11%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Warrior One': {
      n: '\n',
      t: '\t',
      name: 'Warrior One',
      duration: '12:57',
      DURATION: '777',
      damage: '221865',
      'damage-m': '0.22',
      'DAMAGE-k': '222',
      'DAMAGE-m': '0',
      'damage%': '12%',
      dps: '285.54',
      DPS: '286',
      'DPS-k': '0',
      encdps: '281.20',
      ENCDPS: '281',
      'ENCDPS-k': '0',
      hits: '549',
      crithits: '106',
      'crithit%': '19%',
      misses: '0',
      hitfailed: '0',
      swings: '549',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: "Storm's Path-1831",
      MAXHIT: '1831',
      healed: '22595',
      'healed%': '1%',
      enchps: '28.64',
      ENCHPS: '29',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '105',
      cures: '0',
      maxheal: 'Thrill Of Battle-1981',
      MAXHEAL: '1981',
      maxhealward: 'Thrill Of Battle-1981',
      MAXHEALWARD: '1981',
      damagetaken: '241937',
      healstaken: '307511',
      powerdrain: '0',
      powerheal: '0',
      kills: '2',
      deaths: '1',
      threatstr: '+(0)0/-(0)2000',
      threatdelta: '-2000',
      NAME3: 'War',
      NAME4: 'Warr',
      NAME5: 'Warri',
      NAME6: 'Warrio',
      NAME7: 'Warrior',
      NAME8: 'Warrior',
      NAME9: 'Warrior O',
      NAME10: 'Warrior On',
      NAME11: 'Warrior One',
      NAME12: 'Warrior One',
      NAME13: 'Warrior One',
      NAME14: 'Warrior One',
      NAME15: 'Warrior One',
      Last10DPS: '0',
      Last30DPS: '90',
      Last60DPS: '209',
      Job: 'War',
      ParryPct: '11%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Paladin One': {
      n: '\n',
      t: '\t',
      name: 'Paladin One',
      duration: '12:30',
      DURATION: '750',
      damage: '147560',
      'damage-m': '0.15',
      'DAMAGE-k': '148',
      'DAMAGE-m': '0',
      'damage%': '8%',
      dps: '196.75',
      DPS: '197',
      'DPS-k': '0',
      encdps: '187.02',
      ENCDPS: '187',
      'ENCDPS-k': '0',
      hits: '721',
      crithits: '132',
      'crithit%': '18%',
      misses: '0',
      hitfailed: '0',
      swings: '721',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: 'Rage Of Halone-842',
      MAXHIT: '842',
      healed: '10356',
      'healed%': '0%',
      enchps: '13.13',
      ENCHPS: '13',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '72',
      cures: '0',
      maxheal: 'Stoneskin-947',
      MAXHEAL: '947',
      maxhealward: 'Stoneskin-947',
      MAXHEALWARD: '947',
      damagetaken: '305666',
      healstaken: '569140',
      powerdrain: '0',
      powerheal: '266',
      kills: '1',
      deaths: '1',
      threatstr: '+(0)0/-(0)28032',
      threatdelta: '-28032',
      NAME3: 'Pal',
      NAME4: 'Pala',
      NAME5: 'Palad',
      NAME6: 'Paladi',
      NAME7: 'Paladin',
      NAME8: 'Paladin',
      NAME9: 'Paladin O',
      NAME10: 'Paladin On',
      NAME11: 'Paladin One',
      NAME12: 'Paladin One',
      NAME13: 'Paladin One',
      NAME14: 'Paladin One',
      NAME15: 'Paladin One',
      Last10DPS: '0',
      Last30DPS: '0',
      Last60DPS: '28',
      Job: 'Pld',
      ParryPct: '7%',
      BlockPct: '27%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Scholar One': {
      n: '\n',
      t: '\t',
      name: 'Scholar One',
      duration: '13:21',
      DURATION: '801',
      damage: '67373',
      'damage-m': '0.07',
      'DAMAGE-k': '67',
      'DAMAGE-m': '0',
      'damage%': '3%',
      dps: '84.11',
      DPS: '84',
      'DPS-k': '0',
      encdps: '85.39',
      ENCDPS: '85',
      'ENCDPS-k': '0',
      hits: '373',
      crithits: '95',
      'crithit%': '25%',
      misses: '7',
      hitfailed: '0',
      swings: '380',
      tohit: '98.16',
      TOHIT: '98',
      maxhit: 'Energy Drain-1048',
      MAXHIT: '1048',
      healed: '836767',
      'healed%': '46%',
      enchps: '1060.54',
      ENCHPS: '1061',
      'ENCHPS-k': '1',
      critheals: '220',
      'critheal%': '23%',
      heals: '968',
      cures: '0',
      maxheal: 'Galvanize-4222',
      MAXHEAL: '4222',
      maxhealward: 'Galvanize-4222',
      MAXHEALWARD: '4222',
      damagetaken: '70693',
      healstaken: '244571',
      powerdrain: '0',
      powerheal: '12817',
      kills: '0',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Sch',
      NAME4: 'Scho',
      NAME5: 'Schol',
      NAME6: 'Schola',
      NAME7: 'Scholar',
      NAME8: 'Scholar',
      NAME9: 'Scholar O',
      NAME10: 'Scholar On',
      NAME11: 'Scholar One',
      NAME12: 'Scholar One',
      NAME13: 'Scholar One',
      NAME14: 'Scholar One',
      NAME15: 'Scholar One',
      Last10DPS: '0',
      Last30DPS: '154',
      Last60DPS: '134',
      Job: 'Sch',
      ParryPct: '0%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '42%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Limit Break': {
      n: '\n',
      t: '\t',
      name: 'Limit Break',
      duration: '03:36',
      DURATION: '216',
      damage: '34210',
      'damage-m': '0.03',
      'DAMAGE-k': '34',
      'DAMAGE-m': '0',
      'damage%': '1%',
      dps: '158.38',
      DPS: '158',
      'DPS-k': '0',
      encdps: '43.36',
      ENCDPS: '43',
      'ENCDPS-k': '0',
      hits: '1',
      crithits: '0',
      'crithit%': '0%',
      misses: '0',
      hitfailed: '0',
      swings: '1',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: 'Final Heaven-34210',
      MAXHIT: '34210',
      healed: '0',
      'healed%': '0%',
      enchps: '0.00',
      ENCHPS: '0',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '0',
      cures: '0',
      maxheal: '',
      MAXHEAL: '',
      maxhealward: '',
      MAXHEALWARD: '',
      damagetaken: '0',
      healstaken: '0',
      powerdrain: '0',
      powerheal: '0',
      kills: '0',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Lim',
      NAME4: 'Limi',
      NAME5: 'Limit',
      NAME6: 'Limit',
      NAME7: 'Limit B',
      NAME8: 'Limit Br',
      NAME9: 'Limit Bre',
      NAME10: 'Limit Brea',
      NAME11: 'Limit Break',
      NAME12: 'Limit Break',
      NAME13: 'Limit Break',
      NAME14: 'Limit Break',
      NAME15: 'Limit Break',
      Last10DPS: '0',
      Last30DPS: '0',
      Last60DPS: '0',
      Job: '',
      ParryPct: '0%',
      BlockPct: '0%',
      IncToHit: '---',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'WhiteMage One': {
      n: '\n',
      t: '\t',
      name: 'WhiteMage One',
      duration: '13:07',
      DURATION: '787',
      damage: '1980',
      'damage-m': '0.00',
      'DAMAGE-k': '2',
      'DAMAGE-m': '0',
      'damage%': '0%',
      dps: '2.52',
      DPS: '3',
      'DPS-k': '0',
      encdps: '2.51',
      ENCDPS: '3',
      'ENCDPS-k': '0',
      hits: '12',
      crithits: '0',
      'crithit%': '0%',
      misses: '1',
      hitfailed: '0',
      swings: '13',
      tohit: '92.31',
      TOHIT: '92',
      maxhit: 'Stone II-745',
      MAXHIT: '745',
      healed: '926061',
      'healed%': '51%',
      enchps: '1173.71',
      ENCHPS: '1174',
      'ENCHPS-k': '1',
      critheals: '115',
      'critheal%': '7%',
      heals: '1597',
      cures: '4',
      maxheal: 'Benediction-6974',
      MAXHEAL: '6974',
      maxhealward: 'Benediction-6974',
      MAXHEALWARD: '6974',
      damagetaken: '78963',
      healstaken: '127280',
      powerdrain: '0',
      powerheal: '580',
      kills: '1',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Whi',
      NAME4: 'Whit',
      NAME5: 'White',
      NAME6: 'WhiteM',
      NAME7: 'WhiteMa',
      NAME8: 'WhiteMag',
      NAME9: 'WhiteMage',
      NAME10: 'WhiteMage',
      NAME11: 'WhiteMage O',
      NAME12: 'WhiteMage On',
      NAME13: 'WhiteMage One',
      NAME14: 'WhiteMage One',
      NAME15: 'WhiteMage One',
      Last10DPS: '0',
      Last30DPS: '56',
      Last60DPS: '31',
      Job: 'Whm',
      ParryPct: '0%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '42%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Monk Two': {
      n: '\n',
      t: '\t',
      name: 'Monk Two',
      duration: '12:56',
      DURATION: '776',
      damage: '355882',
      'damage-m': '0.36',
      'DAMAGE-k': '356',
      'DAMAGE-m': '0',
      'damage%': '19%',
      dps: '458.61',
      DPS: '459',
      'DPS-k': '0',
      encdps: '451.05',
      ENCDPS: '451',
      'ENCDPS-k': '0',
      hits: '811',
      crithits: '200',
      'crithit%': '25%',
      misses: '2',
      hitfailed: '0',
      swings: '813',
      tohit: '99.75',
      TOHIT: '100',
      maxhit: 'True Strike-1392',
      MAXHIT: '1392',
      healed: '0',
      'healed%': '0%',
      enchps: '0.00',
      ENCHPS: '0',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '0',
      cures: '0',
      maxheal: '',
      MAXHEAL: '',
      maxhealward: '',
      MAXHEALWARD: '',
      damagetaken: '100037',
      healstaken: '146767',
      powerdrain: '0',
      powerheal: '0',
      kills: '3',
      deaths: '1',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Mon',
      NAME4: 'Monk',
      NAME5: 'Monk',
      NAME6: 'Monk T',
      NAME7: 'Monk Tw',
      NAME8: 'Monk Two',
      NAME9: 'Monk Two',
      NAME10: 'Monk Two',
      NAME11: 'Monk Two',
      NAME12: 'Monk Two',
      NAME13: 'Monk Two',
      NAME14: 'Monk Two',
      NAME15: 'Monk Two',
      Last10DPS: '0',
      Last30DPS: '95',
      Last60DPS: '292',
      Job: 'Mnk',
      ParryPct: '9%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Bard Two': {
      n: '\n',
      t: '\t',
      name: 'Bard Two',
      duration: '13:09',
      DURATION: '789',
      damage: '350064',
      'damage-m': '0.35',
      'DAMAGE-k': '350',
      'DAMAGE-m': '0',
      'damage%': '19%',
      dps: '443.68',
      DPS: '444',
      'DPS-k': '0',
      encdps: '443.68',
      ENCDPS: '444',
      'ENCDPS-k': '0',
      hits: '1240',
      crithits: '475',
      'crithit%': '38%',
      misses: '0',
      hitfailed: '0',
      swings: '1240',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: 'Heavy Shot-1016',
      MAXHIT: '1016',
      healed: '2798',
      'healed%': '0%',
      enchps: '3.55',
      ENCHPS: '4',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '3',
      cures: '0',
      maxheal: 'Second Wind-1005',
      MAXHEAL: '1005',
      maxhealward: 'Second Wind-1005',
      MAXHEALWARD: '1005',
      damagetaken: '77145',
      healstaken: '122216',
      powerdrain: '0',
      powerheal: '0',
      kills: '1',
      deaths: '1',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Bar',
      NAME4: 'Bard',
      NAME5: 'Bard',
      NAME6: 'Bard T',
      NAME7: 'Bard Two',
      NAME8: 'Bard Two',
      NAME9: 'Bard Two',
      NAME10: 'Bard Two',
      NAME11: 'Bard Two',
      NAME12: 'Bard Two',
      NAME13: 'Bard Two',
      NAME14: 'Bard Two',
      NAME15: 'Bard Two',
      Last10DPS: '0',
      Last30DPS: '293',
      Last60DPS: '354',
      Job: 'Brd',
      ParryPct: '50%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '34%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Dragoon Two': {
      n: '\n',
      t: '\t',
      name: 'Dragoon Two',
      duration: '13:06',
      DURATION: '786',
      damage: '331961',
      'damage-m': '0.33',
      'DAMAGE-k': '332',
      'DAMAGE-m': '0',
      'damage%': '18%',
      dps: '422.34',
      DPS: '422',
      'DPS-k': '0',
      encdps: '420.74',
      ENCDPS: '421',
      'ENCDPS-k': '0',
      hits: '830',
      crithits: '141',
      'crithit%': '17%',
      misses: '1',
      hitfailed: '0',
      swings: '831',
      tohit: '99.88',
      TOHIT: '100',
      maxhit: 'Full Thrust-2488',
      MAXHIT: '2488',
      healed: '11656',
      'healed%': '0%',
      enchps: '14.77',
      ENCHPS: '15',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '26',
      cures: '0',
      maxheal: 'Second Wind-1108',
      MAXHEAL: '1108',
      maxhealward: 'Second Wind-1108',
      MAXHEALWARD: '1108',
      damagetaken: '90082',
      healstaken: '155129',
      powerdrain: '0',
      powerheal: '0',
      kills: '2',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Dra',
      NAME4: 'Drag',
      NAME5: 'Drago',
      NAME6: 'Dragoo',
      NAME7: 'Dragoon',
      NAME8: 'Dragoon',
      NAME9: 'Dragoon T',
      NAME10: 'Dragoon Tw',
      NAME11: 'Dragoon Two',
      NAME12: 'Dragoon Two',
      NAME13: 'Dragoon Two',
      NAME14: 'Dragoon Two',
      NAME15: 'Dragoon Two',
      Last10DPS: '0',
      Last30DPS: '168',
      Last60DPS: '353',
      Job: 'Drg',
      ParryPct: '55%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'BlackMage Two': {
      n: '\n',
      t: '\t',
      name: 'BlackMage Two',
      duration: '13:06',
      DURATION: '786',
      damage: '329454',
      'damage-m': '0.33',
      'DAMAGE-k': '329',
      'DAMAGE-m': '0',
      'damage%': '17%',
      dps: '419.15',
      DPS: '419',
      'DPS-k': '0',
      encdps: '417.56',
      ENCDPS: '418',
      'ENCDPS-k': '0',
      hits: '405',
      crithits: '57',
      'crithit%': '14%',
      misses: '0',
      hitfailed: '0',
      swings: '405',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: 'Flare-3606',
      MAXHIT: '3606',
      healed: '0',
      'healed%': '0%',
      enchps: '0.00',
      ENCHPS: '0',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '0',
      cures: '0',
      maxheal: '',
      MAXHEAL: '',
      maxhealward: '',
      MAXHEALWARD: '',
      damagetaken: '87977',
      healstaken: '139709',
      powerdrain: '0',
      powerheal: '4820',
      kills: '0',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Bla',
      NAME4: 'Blac',
      NAME5: 'Black',
      NAME6: 'BlackM',
      NAME7: 'BlackMa',
      NAME8: 'BlackMag',
      NAME9: 'BlackMage',
      NAME10: 'BlackMage',
      NAME11: 'BlackMage T',
      NAME12: 'BlackMage Tw',
      NAME13: 'BlackMage Two',
      NAME14: 'BlackMage Two',
      NAME15: 'BlackMage Two',
      Last10DPS: '0',
      Last30DPS: '206',
      Last60DPS: '293',
      Job: 'Blm',
      ParryPct: '11%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Warrior Two': {
      n: '\n',
      t: '\t',
      name: 'Warrior Two',
      duration: '12:57',
      DURATION: '777',
      damage: '221865',
      'damage-m': '0.22',
      'DAMAGE-k': '222',
      'DAMAGE-m': '0',
      'damage%': '12%',
      dps: '285.54',
      DPS: '286',
      'DPS-k': '0',
      encdps: '281.20',
      ENCDPS: '281',
      'ENCDPS-k': '0',
      hits: '549',
      crithits: '106',
      'crithit%': '19%',
      misses: '0',
      hitfailed: '0',
      swings: '549',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: "Storm's Path-1831",
      MAXHIT: '1831',
      healed: '22595',
      'healed%': '1%',
      enchps: '28.64',
      ENCHPS: '29',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '105',
      cures: '0',
      maxheal: 'Thrill Of Battle-1981',
      MAXHEAL: '1981',
      maxhealward: 'Thrill Of Battle-1981',
      MAXHEALWARD: '1981',
      damagetaken: '241937',
      healstaken: '307511',
      powerdrain: '0',
      powerheal: '0',
      kills: '2',
      deaths: '1',
      threatstr: '+(0)0/-(0)2000',
      threatdelta: '-2000',
      NAME3: 'War',
      NAME4: 'Warr',
      NAME5: 'Warri',
      NAME6: 'Warrio',
      NAME7: 'Warrior',
      NAME8: 'Warrior',
      NAME9: 'Warrior T',
      NAME10: 'Warrior Tw',
      NAME11: 'Warrior Two',
      NAME12: 'Warrior Two',
      NAME13: 'Warrior Two',
      NAME14: 'Warrior Two',
      NAME15: 'Warrior Two',
      Last10DPS: '0',
      Last30DPS: '90',
      Last60DPS: '209',
      Job: 'War',
      ParryPct: '11%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Paladin Two': {
      n: '\n',
      t: '\t',
      name: 'Paladin Two',
      duration: '12:30',
      DURATION: '750',
      damage: '147560',
      'damage-m': '0.15',
      'DAMAGE-k': '148',
      'DAMAGE-m': '0',
      'damage%': '8%',
      dps: '196.75',
      DPS: '197',
      'DPS-k': '0',
      encdps: '187.02',
      ENCDPS: '187',
      'ENCDPS-k': '0',
      hits: '721',
      crithits: '132',
      'crithit%': '18%',
      misses: '0',
      hitfailed: '0',
      swings: '721',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: 'Rage Of Halone-842',
      MAXHIT: '842',
      healed: '10356',
      'healed%': '0%',
      enchps: '13.13',
      ENCHPS: '13',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '72',
      cures: '0',
      maxheal: 'Stoneskin-947',
      MAXHEAL: '947',
      maxhealward: 'Stoneskin-947',
      MAXHEALWARD: '947',
      damagetaken: '305666',
      healstaken: '569140',
      powerdrain: '0',
      powerheal: '266',
      kills: '1',
      deaths: '1',
      threatstr: '+(0)0/-(0)28032',
      threatdelta: '-28032',
      NAME3: 'Pal',
      NAME4: 'Pala',
      NAME5: 'Palad',
      NAME6: 'Paladi',
      NAME7: 'Paladin',
      NAME8: 'Paladin',
      NAME9: 'Paladin T',
      NAME10: 'Paladin Tw',
      NAME11: 'Paladin Two',
      NAME12: 'Paladin Two',
      NAME13: 'Paladin Two',
      NAME14: 'Paladin Two',
      NAME15: 'Paladin Two',
      Last10DPS: '0',
      Last30DPS: '0',
      Last60DPS: '28',
      Job: 'Pld',
      ParryPct: '7%',
      BlockPct: '27%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Scholar Two': {
      n: '\n',
      t: '\t',
      name: 'Scholar Two',
      duration: '13:21',
      DURATION: '801',
      damage: '67373',
      'damage-m': '0.07',
      'DAMAGE-k': '67',
      'DAMAGE-m': '0',
      'damage%': '3%',
      dps: '84.11',
      DPS: '84',
      'DPS-k': '0',
      encdps: '85.39',
      ENCDPS: '85',
      'ENCDPS-k': '0',
      hits: '373',
      crithits: '95',
      'crithit%': '25%',
      misses: '7',
      hitfailed: '0',
      swings: '380',
      tohit: '98.16',
      TOHIT: '98',
      maxhit: 'Energy Drain-1048',
      MAXHIT: '1048',
      healed: '836767',
      'healed%': '46%',
      enchps: '1060.54',
      ENCHPS: '1061',
      'ENCHPS-k': '1',
      critheals: '220',
      'critheal%': '23%',
      heals: '968',
      cures: '0',
      maxheal: 'Galvanize-4222',
      MAXHEAL: '4222',
      maxhealward: 'Galvanize-4222',
      MAXHEALWARD: '4222',
      damagetaken: '70693',
      healstaken: '244571',
      powerdrain: '0',
      powerheal: '12817',
      kills: '0',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Sch',
      NAME4: 'Scho',
      NAME5: 'Schol',
      NAME6: 'Schola',
      NAME7: 'Scholar',
      NAME8: 'Scholar',
      NAME9: 'Scholar T',
      NAME10: 'Scholar Tw',
      NAME11: 'Scholar Two',
      NAME12: 'Scholar Two',
      NAME13: 'Scholar Two',
      NAME14: 'Scholar Two',
      NAME15: 'Scholar Two',
      Last10DPS: '0',
      Last30DPS: '154',
      Last60DPS: '134',
      Job: 'Sch',
      ParryPct: '0%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '42%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'WhiteMage Two': {
      n: '\n',
      t: '\t',
      name: 'WhiteMage Two',
      duration: '13:07',
      DURATION: '787',
      damage: '1980',
      'damage-m': '0.00',
      'DAMAGE-k': '2',
      'DAMAGE-m': '0',
      'damage%': '0%',
      dps: '2.52',
      DPS: '3',
      'DPS-k': '0',
      encdps: '2.51',
      ENCDPS: '3',
      'ENCDPS-k': '0',
      hits: '12',
      crithits: '0',
      'crithit%': '0%',
      misses: '1',
      hitfailed: '0',
      swings: '13',
      tohit: '92.31',
      TOHIT: '92',
      maxhit: 'Stone II-745',
      MAXHIT: '745',
      healed: '926061',
      'healed%': '51%',
      enchps: '1173.71',
      ENCHPS: '1174',
      'ENCHPS-k': '1',
      critheals: '115',
      'critheal%': '7%',
      heals: '1597',
      cures: '4',
      maxheal: 'Benediction-6974',
      MAXHEAL: '6974',
      maxhealward: 'Benediction-6974',
      MAXHEALWARD: '6974',
      damagetaken: '78963',
      healstaken: '127280',
      powerdrain: '0',
      powerheal: '580',
      kills: '1',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Whi',
      NAME4: 'Whit',
      NAME5: 'White',
      NAME6: 'WhiteM',
      NAME7: 'WhiteMa',
      NAME8: 'WhiteMag',
      NAME9: 'WhiteMage',
      NAME10: 'WhiteMage',
      NAME11: 'WhiteMage T',
      NAME12: 'WhiteMage Tw',
      NAME13: 'WhiteMage Two',
      NAME14: 'WhiteMage Two',
      NAME15: 'WhiteMage Two',
      Last10DPS: '0',
      Last30DPS: '56',
      Last60DPS: '31',
      Job: 'Whm',
      ParryPct: '0%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '42%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Monk Three': {
      n: '\n',
      t: '\t',
      name: 'Monk Three',
      duration: '12:56',
      DURATION: '776',
      damage: '355882',
      'damage-m': '0.36',
      'DAMAGE-k': '356',
      'DAMAGE-m': '0',
      'damage%': '19%',
      dps: '458.61',
      DPS: '459',
      'DPS-k': '0',
      encdps: '451.05',
      ENCDPS: '451',
      'ENCDPS-k': '0',
      hits: '811',
      crithits: '200',
      'crithit%': '25%',
      misses: '2',
      hitfailed: '0',
      swings: '813',
      tohit: '99.75',
      TOHIT: '100',
      maxhit: 'True Strike-1392',
      MAXHIT: '1392',
      healed: '0',
      'healed%': '0%',
      enchps: '0.00',
      ENCHPS: '0',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '0',
      cures: '0',
      maxheal: '',
      MAXHEAL: '',
      maxhealward: '',
      MAXHEALWARD: '',
      damagetaken: '100037',
      healstaken: '146767',
      powerdrain: '0',
      powerheal: '0',
      kills: '3',
      deaths: '1',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Mon',
      NAME4: 'Monk',
      NAME5: 'Monk',
      NAME6: 'Monk T',
      NAME7: 'Monk Th',
      NAME8: 'Monk Thr',
      NAME9: 'Monk Thre',
      NAME10: 'Monk Three',
      NAME11: 'Monk Three',
      NAME12: 'Monk Three',
      NAME13: 'Monk Three',
      NAME14: 'Monk Three',
      NAME15: 'Monk Three',
      Last10DPS: '0',
      Last30DPS: '95',
      Last60DPS: '292',
      Job: 'Mnk',
      ParryPct: '9%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Bard Three': {
      n: '\n',
      t: '\t',
      name: 'Bard Three',
      duration: '13:09',
      DURATION: '789',
      damage: '350064',
      'damage-m': '0.35',
      'DAMAGE-k': '350',
      'DAMAGE-m': '0',
      'damage%': '19%',
      dps: '443.68',
      DPS: '444',
      'DPS-k': '0',
      encdps: '443.68',
      ENCDPS: '444',
      'ENCDPS-k': '0',
      hits: '1240',
      crithits: '475',
      'crithit%': '38%',
      misses: '0',
      hitfailed: '0',
      swings: '1240',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: 'Heavy Shot-1016',
      MAXHIT: '1016',
      healed: '2798',
      'healed%': '0%',
      enchps: '3.55',
      ENCHPS: '4',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '3',
      cures: '0',
      maxheal: 'Second Wind-1005',
      MAXHEAL: '1005',
      maxhealward: 'Second Wind-1005',
      MAXHEALWARD: '1005',
      damagetaken: '77145',
      healstaken: '122216',
      powerdrain: '0',
      powerheal: '0',
      kills: '1',
      deaths: '1',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Bar',
      NAME4: 'Bard',
      NAME5: 'Bard',
      NAME6: 'Bard T',
      NAME7: 'Bard Th',
      NAME8: 'Bard Thr',
      NAME9: 'Bard Thre',
      NAME10: 'Bard Three',
      NAME11: 'Bard Three',
      NAME12: 'Bard Three',
      NAME13: 'Bard Three',
      NAME14: 'Bard Three',
      NAME15: 'Bard Three',
      Last10DPS: '0',
      Last30DPS: '293',
      Last60DPS: '354',
      Job: 'Brd',
      ParryPct: '50%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '34%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Dragoon Three': {
      n: '\n',
      t: '\t',
      name: 'Dragoon Three',
      duration: '13:06',
      DURATION: '786',
      damage: '331961',
      'damage-m': '0.33',
      'DAMAGE-k': '332',
      'DAMAGE-m': '0',
      'damage%': '18%',
      dps: '422.34',
      DPS: '422',
      'DPS-k': '0',
      encdps: '420.74',
      ENCDPS: '421',
      'ENCDPS-k': '0',
      hits: '830',
      crithits: '141',
      'crithit%': '17%',
      misses: '1',
      hitfailed: '0',
      swings: '831',
      tohit: '99.88',
      TOHIT: '100',
      maxhit: 'Full Thrust-2488',
      MAXHIT: '2488',
      healed: '11656',
      'healed%': '0%',
      enchps: '14.77',
      ENCHPS: '15',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '26',
      cures: '0',
      maxheal: 'Second Wind-1108',
      MAXHEAL: '1108',
      maxhealward: 'Second Wind-1108',
      MAXHEALWARD: '1108',
      damagetaken: '90082',
      healstaken: '155129',
      powerdrain: '0',
      powerheal: '0',
      kills: '2',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Dra',
      NAME4: 'Drag',
      NAME5: 'Drago',
      NAME6: 'Dragoo',
      NAME7: 'Dragoon',
      NAME8: 'Dragoon',
      NAME9: 'Dragoon T',
      NAME10: 'Dragoon Th',
      NAME11: 'Dragoon Thr',
      NAME12: 'Dragoon Thre',
      NAME13: 'Dragoon Three',
      NAME14: 'Dragoon Three',
      NAME15: 'Dragoon Three',
      Last10DPS: '0',
      Last30DPS: '168',
      Last60DPS: '353',
      Job: 'Drg',
      ParryPct: '55%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'BlackMage Three': {
      n: '\n',
      t: '\t',
      name: 'BlackMage Three',
      duration: '13:06',
      DURATION: '786',
      damage: '329454',
      'damage-m': '0.33',
      'DAMAGE-k': '329',
      'DAMAGE-m': '0',
      'damage%': '17%',
      dps: '419.15',
      DPS: '419',
      'DPS-k': '0',
      encdps: '417.56',
      ENCDPS: '418',
      'ENCDPS-k': '0',
      hits: '405',
      crithits: '57',
      'crithit%': '14%',
      misses: '0',
      hitfailed: '0',
      swings: '405',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: 'Flare-3606',
      MAXHIT: '3606',
      healed: '0',
      'healed%': '0%',
      enchps: '0.00',
      ENCHPS: '0',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '0',
      cures: '0',
      maxheal: '',
      MAXHEAL: '',
      maxhealward: '',
      MAXHEALWARD: '',
      damagetaken: '87977',
      healstaken: '139709',
      powerdrain: '0',
      powerheal: '4820',
      kills: '0',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Bla',
      NAME4: 'Blac',
      NAME5: 'Black',
      NAME6: 'BlackM',
      NAME7: 'BlackMa',
      NAME8: 'BlackMag',
      NAME9: 'BlackMage',
      NAME10: 'BlackMage',
      NAME11: 'BlackMage T',
      NAME12: 'BlackMage Th',
      NAME13: 'BlackMage Thr',
      NAME14: 'BlackMage Thre',
      NAME15: 'BlackMage Three',
      Last10DPS: '0',
      Last30DPS: '206',
      Last60DPS: '293',
      Job: 'Blm',
      ParryPct: '11%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Warrior Three': {
      n: '\n',
      t: '\t',
      name: 'Warrior Three',
      duration: '12:57',
      DURATION: '777',
      damage: '221865',
      'damage-m': '0.22',
      'DAMAGE-k': '222',
      'DAMAGE-m': '0',
      'damage%': '12%',
      dps: '285.54',
      DPS: '286',
      'DPS-k': '0',
      encdps: '281.20',
      ENCDPS: '281',
      'ENCDPS-k': '0',
      hits: '549',
      crithits: '106',
      'crithit%': '19%',
      misses: '0',
      hitfailed: '0',
      swings: '549',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: "Storm's Path-1831",
      MAXHIT: '1831',
      healed: '22595',
      'healed%': '1%',
      enchps: '28.64',
      ENCHPS: '29',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '105',
      cures: '0',
      maxheal: 'Thrill Of Battle-1981',
      MAXHEAL: '1981',
      maxhealward: 'Thrill Of Battle-1981',
      MAXHEALWARD: '1981',
      damagetaken: '241937',
      healstaken: '307511',
      powerdrain: '0',
      powerheal: '0',
      kills: '2',
      deaths: '1',
      threatstr: '+(0)0/-(0)2000',
      threatdelta: '-2000',
      NAME3: 'War',
      NAME4: 'Warr',
      NAME5: 'Warri',
      NAME6: 'Warrio',
      NAME7: 'Warrior',
      NAME8: 'Warrior',
      NAME9: 'Warrior T',
      NAME10: 'Warrior Th',
      NAME11: 'Warrior Thr',
      NAME12: 'Warrior Thre',
      NAME13: 'Warrior Three',
      NAME14: 'Warrior Three',
      NAME15: 'Warrior Three',
      Last10DPS: '0',
      Last30DPS: '90',
      Last60DPS: '209',
      Job: 'War',
      ParryPct: '11%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Paladin Three': {
      n: '\n',
      t: '\t',
      name: 'Paladin Three',
      duration: '12:30',
      DURATION: '750',
      damage: '147560',
      'damage-m': '0.15',
      'DAMAGE-k': '148',
      'DAMAGE-m': '0',
      'damage%': '8%',
      dps: '196.75',
      DPS: '197',
      'DPS-k': '0',
      encdps: '187.02',
      ENCDPS: '187',
      'ENCDPS-k': '0',
      hits: '721',
      crithits: '132',
      'crithit%': '18%',
      misses: '0',
      hitfailed: '0',
      swings: '721',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: 'Rage Of Halone-842',
      MAXHIT: '842',
      healed: '10356',
      'healed%': '0%',
      enchps: '13.13',
      ENCHPS: '13',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '72',
      cures: '0',
      maxheal: 'Stoneskin-947',
      MAXHEAL: '947',
      maxhealward: 'Stoneskin-947',
      MAXHEALWARD: '947',
      damagetaken: '305666',
      healstaken: '569140',
      powerdrain: '0',
      powerheal: '266',
      kills: '1',
      deaths: '1',
      threatstr: '+(0)0/-(0)28032',
      threatdelta: '-28032',
      NAME3: 'Pal',
      NAME4: 'Pala',
      NAME5: 'Palad',
      NAME6: 'Paladi',
      NAME7: 'Paladin',
      NAME8: 'Paladin',
      NAME9: 'Paladin T',
      NAME10: 'Paladin Th',
      NAME11: 'Paladin Thr',
      NAME12: 'Paladin Thre',
      NAME13: 'Paladin Three',
      NAME14: 'Paladin Three',
      NAME15: 'Paladin Three',
      Last10DPS: '0',
      Last30DPS: '0',
      Last60DPS: '28',
      Job: 'Pld',
      ParryPct: '7%',
      BlockPct: '27%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Scholar Three': {
      n: '\n',
      t: '\t',
      name: 'Scholar Three',
      duration: '13:21',
      DURATION: '801',
      damage: '67373',
      'damage-m': '0.07',
      'DAMAGE-k': '67',
      'DAMAGE-m': '0',
      'damage%': '3%',
      dps: '84.11',
      DPS: '84',
      'DPS-k': '0',
      encdps: '85.39',
      ENCDPS: '85',
      'ENCDPS-k': '0',
      hits: '373',
      crithits: '95',
      'crithit%': '25%',
      misses: '7',
      hitfailed: '0',
      swings: '380',
      tohit: '98.16',
      TOHIT: '98',
      maxhit: 'Energy Drain-1048',
      MAXHIT: '1048',
      healed: '836767',
      'healed%': '46%',
      enchps: '1060.54',
      ENCHPS: '1061',
      'ENCHPS-k': '1',
      critheals: '220',
      'critheal%': '23%',
      heals: '968',
      cures: '0',
      maxheal: 'Galvanize-4222',
      MAXHEAL: '4222',
      maxhealward: 'Galvanize-4222',
      MAXHEALWARD: '4222',
      damagetaken: '70693',
      healstaken: '244571',
      powerdrain: '0',
      powerheal: '12817',
      kills: '0',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Sch',
      NAME4: 'Scho',
      NAME5: 'Schol',
      NAME6: 'Schola',
      NAME7: 'Scholar',
      NAME8: 'Scholar',
      NAME9: 'Scholar T',
      NAME10: 'Scholar Th',
      NAME11: 'Scholar Thr',
      NAME12: 'Scholar Thre',
      NAME13: 'Scholar Three',
      NAME14: 'Scholar Three',
      NAME15: 'Scholar Three',
      Last10DPS: '0',
      Last30DPS: '154',
      Last60DPS: '134',
      Job: 'Sch',
      ParryPct: '0%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '42%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'WhiteMage Three': {
      n: '\n',
      t: '\t',
      name: 'WhiteMage Three',
      duration: '13:07',
      DURATION: '787',
      damage: '1980',
      'damage-m': '0.00',
      'DAMAGE-k': '2',
      'DAMAGE-m': '0',
      'damage%': '0%',
      dps: '2.52',
      DPS: '3',
      'DPS-k': '0',
      encdps: '2.51',
      ENCDPS: '3',
      'ENCDPS-k': '0',
      hits: '12',
      crithits: '0',
      'crithit%': '0%',
      misses: '1',
      hitfailed: '0',
      swings: '13',
      tohit: '92.31',
      TOHIT: '92',
      maxhit: 'Stone II-745',
      MAXHIT: '745',
      healed: '926061',
      'healed%': '51%',
      enchps: '1173.71',
      ENCHPS: '1174',
      'ENCHPS-k': '1',
      critheals: '115',
      'critheal%': '7%',
      heals: '1597',
      cures: '4',
      maxheal: 'Benediction-6974',
      MAXHEAL: '6974',
      maxhealward: 'Benediction-6974',
      MAXHEALWARD: '6974',
      damagetaken: '78963',
      healstaken: '127280',
      powerdrain: '0',
      powerheal: '580',
      kills: '1',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Whi',
      NAME4: 'Whit',
      NAME5: 'White',
      NAME6: 'WhiteM',
      NAME7: 'WhiteMa',
      NAME8: 'WhiteMag',
      NAME9: 'WhiteMage',
      NAME10: 'WhiteMage',
      NAME11: 'WhiteMage T',
      NAME12: 'WhiteMage Th',
      NAME13: 'WhiteMage Thr',
      NAME14: 'WhiteMage Thre',
      NAME15: 'WhiteMage Three',
      Last10DPS: '0',
      Last30DPS: '56',
      Last60DPS: '31',
      Job: 'Whm',
      ParryPct: '0%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '42%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
  },
  isActive: true,
};
var ActFakeData8 = {
  Encounter: {
    n: '\n',
    t: '\t',
    title: 'Encounter',
    duration: '13:09',
    DURATION: '789',
    damage: '1840349',
    'damage-m': '1.84',
    'DAMAGE-k': '1840',
    'DAMAGE-m': '2',
    dps: '2332.51',
    DPS: '2333',
    'DPS-k': '2',
    encdps: '2332.51',
    ENCDPS: '2333',
    'ENCDPS-k': '2',
    hits: '4942',
    crithits: '1206',
    'crithit%': '0%',
    misses: '11',
    hitfailed: '0',
    swings: '4953',
    tohit: '98.90',
    TOHIT: '99',
    maxhit: 'Limit Break-Final Heaven-34210',
    MAXHIT: 'Limit Break-34210',
    healed: '1810233',
    enchps: '2294.34',
    ENCHPS: '2294',
    'ENCHPS-k': '2',
    critheals: '1206',
    'critheal%': '0%',
    heals: '2771',
    cures: '4',
    maxheal: 'White Mage One-Benediction-6974',
    MAXHEAL: 'White Mage One-6974',
    maxhealward: 'White Mage One-Benediction-6974',
    MAXHEALWARD: 'White Mage One-6974',
    damagetaken: '1052500',
    healstaken: '1812323',
    powerdrain: '0',
    powerheal: '18483',
    kills: '10',
    deaths: '4',
    CurrentZoneName: 'An instance',
    Last10DPS: '2095',
    Last30DPS: '1922',
    Last60DPS: '2347',
  },
  Combatant: {
    'Monk One': {
      n: '\n',
      t: '\t',
      name: 'YOU',
      duration: '12:56',
      DURATION: '776',
      damage: '355882',
      'damage-m': '0.36',
      'DAMAGE-k': '356',
      'DAMAGE-m': '0',
      'damage%': '19%',
      dps: '458.61',
      DPS: '459',
      'DPS-k': '0',
      encdps: '451.05',
      ENCDPS: '451',
      'ENCDPS-k': '0',
      hits: '811',
      crithits: '200',
      'crithit%': '25%',
      misses: '2',
      hitfailed: '0',
      swings: '813',
      tohit: '99.75',
      TOHIT: '100',
      maxhit: 'True Strike-1392',
      MAXHIT: '1392',
      healed: '0',
      'healed%': '0%',
      enchps: '0.00',
      ENCHPS: '0',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '0',
      cures: '0',
      maxheal: '',
      MAXHEAL: '',
      maxhealward: '',
      MAXHEALWARD: '',
      damagetaken: '100037',
      healstaken: '146767',
      powerdrain: '0',
      powerheal: '0',
      kills: '3',
      deaths: '1',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'YOU',
      NAME4: 'YOU',
      NAME5: 'YOU',
      NAME6: 'YOU',
      NAME7: 'YOU',
      NAME8: 'YOU',
      NAME9: 'YOU',
      NAME10: 'YOU',
      NAME11: 'YOU',
      NAME12: 'YOU',
      NAME13: 'YOU',
      NAME14: 'YOU',
      NAME15: 'YOU',
      Last10DPS: '0',
      Last30DPS: '95',
      Last60DPS: '292',
      Job: 'Mnk',
      ParryPct: '9%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Bard One': {
      n: '\n',
      t: '\t',
      name: 'Bard One',
      duration: '13:09',
      DURATION: '789',
      damage: '350064',
      'damage-m': '0.35',
      'DAMAGE-k': '350',
      'DAMAGE-m': '0',
      'damage%': '19%',
      dps: '443.68',
      DPS: '444',
      'DPS-k': '0',
      encdps: '443.68',
      ENCDPS: '444',
      'ENCDPS-k': '0',
      hits: '1240',
      crithits: '475',
      'crithit%': '38%',
      misses: '0',
      hitfailed: '0',
      swings: '1240',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: 'Heavy Shot-1016',
      MAXHIT: '1016',
      healed: '2798',
      'healed%': '0%',
      enchps: '3.55',
      ENCHPS: '4',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '3',
      cures: '0',
      maxheal: 'Second Wind-1005',
      MAXHEAL: '1005',
      maxhealward: 'Second Wind-1005',
      MAXHEALWARD: '1005',
      damagetaken: '77145',
      healstaken: '122216',
      powerdrain: '0',
      powerheal: '0',
      kills: '1',
      deaths: '1',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Bar',
      NAME4: 'Bard',
      NAME5: 'Bard',
      NAME6: 'Bard O',
      NAME7: 'Bard On',
      NAME8: 'Bard One',
      NAME9: 'Bard One',
      NAME10: 'Bard One',
      NAME11: 'Bard One',
      NAME12: 'Bard One',
      NAME13: 'Bard One',
      NAME14: 'Bard One',
      NAME15: 'Bard One',
      Last10DPS: '0',
      Last30DPS: '293',
      Last60DPS: '354',
      Job: 'Brd',
      ParryPct: '50%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '34%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Dragoon One': {
      n: '\n',
      t: '\t',
      name: 'Dragoon One',
      duration: '13:06',
      DURATION: '786',
      damage: '331961',
      'damage-m': '0.33',
      'DAMAGE-k': '332',
      'DAMAGE-m': '0',
      'damage%': '18%',
      dps: '422.34',
      DPS: '422',
      'DPS-k': '0',
      encdps: '420.74',
      ENCDPS: '421',
      'ENCDPS-k': '0',
      hits: '830',
      crithits: '141',
      'crithit%': '17%',
      misses: '1',
      hitfailed: '0',
      swings: '831',
      tohit: '99.88',
      TOHIT: '100',
      maxhit: 'Full Thrust-2488',
      MAXHIT: '2488',
      healed: '11656',
      'healed%': '0%',
      enchps: '14.77',
      ENCHPS: '15',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '26',
      cures: '0',
      maxheal: 'Second Wind-1108',
      MAXHEAL: '1108',
      maxhealward: 'Second Wind-1108',
      MAXHEALWARD: '1108',
      damagetaken: '90082',
      healstaken: '155129',
      powerdrain: '0',
      powerheal: '0',
      kills: '2',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Dra',
      NAME4: 'Drag',
      NAME5: 'Drago',
      NAME6: 'Dragoo',
      NAME7: 'Dragoon',
      NAME8: 'Dragoon',
      NAME9: 'Dragoon O',
      NAME10: 'Dragoon On',
      NAME11: 'Dragoon One',
      NAME12: 'Dragoon One',
      NAME13: 'Dragoon One',
      NAME14: 'Dragoon One',
      NAME15: 'Dragoon One',
      Last10DPS: '0',
      Last30DPS: '168',
      Last60DPS: '353',
      Job: 'Drg',
      ParryPct: '55%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'BlackMage One': {
      n: '\n',
      t: '\t',
      name: 'BlackMage One',
      duration: '13:06',
      DURATION: '786',
      damage: '329454',
      'damage-m': '0.33',
      'DAMAGE-k': '329',
      'DAMAGE-m': '0',
      'damage%': '17%',
      dps: '419.15',
      DPS: '419',
      'DPS-k': '0',
      encdps: '417.56',
      ENCDPS: '418',
      'ENCDPS-k': '0',
      hits: '405',
      crithits: '57',
      'crithit%': '14%',
      misses: '0',
      hitfailed: '0',
      swings: '405',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: 'Flare-3606',
      MAXHIT: '3606',
      healed: '0',
      'healed%': '0%',
      enchps: '0.00',
      ENCHPS: '0',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '0',
      cures: '0',
      maxheal: '',
      MAXHEAL: '',
      maxhealward: '',
      MAXHEALWARD: '',
      damagetaken: '87977',
      healstaken: '139709',
      powerdrain: '0',
      powerheal: '4820',
      kills: '0',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Bla',
      NAME4: 'Blac',
      NAME5: 'Black',
      NAME6: 'BlackM',
      NAME7: 'BlackMa',
      NAME8: 'BlackMag',
      NAME9: 'BlackMage',
      NAME10: 'BlackMage',
      NAME11: 'BlackMage O',
      NAME12: 'BlackMage On',
      NAME13: 'BlackMage One',
      NAME14: 'BlackMage One',
      NAME15: 'BlackMage One',
      Last10DPS: '0',
      Last30DPS: '206',
      Last60DPS: '293',
      Job: 'Blm',
      ParryPct: '11%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Warrior One': {
      n: '\n',
      t: '\t',
      name: 'Warrior One',
      duration: '12:57',
      DURATION: '777',
      damage: '221865',
      'damage-m': '0.22',
      'DAMAGE-k': '222',
      'DAMAGE-m': '0',
      'damage%': '12%',
      dps: '285.54',
      DPS: '286',
      'DPS-k': '0',
      encdps: '281.20',
      ENCDPS: '281',
      'ENCDPS-k': '0',
      hits: '549',
      crithits: '106',
      'crithit%': '19%',
      misses: '0',
      hitfailed: '0',
      swings: '549',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: "Storm's Path-1831",
      MAXHIT: '1831',
      healed: '22595',
      'healed%': '1%',
      enchps: '28.64',
      ENCHPS: '29',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '105',
      cures: '0',
      maxheal: 'Thrill Of Battle-1981',
      MAXHEAL: '1981',
      maxhealward: 'Thrill Of Battle-1981',
      MAXHEALWARD: '1981',
      damagetaken: '241937',
      healstaken: '307511',
      powerdrain: '0',
      powerheal: '0',
      kills: '2',
      deaths: '1',
      threatstr: '+(0)0/-(0)2000',
      threatdelta: '-2000',
      NAME3: 'War',
      NAME4: 'Warr',
      NAME5: 'Warri',
      NAME6: 'Warrio',
      NAME7: 'Warrior',
      NAME8: 'Warrior',
      NAME9: 'Warrior O',
      NAME10: 'Warrior On',
      NAME11: 'Warrior One',
      NAME12: 'Warrior One',
      NAME13: 'Warrior One',
      NAME14: 'Warrior One',
      NAME15: 'Warrior One',
      Last10DPS: '0',
      Last30DPS: '90',
      Last60DPS: '209',
      Job: 'War',
      ParryPct: '11%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Paladin One': {
      n: '\n',
      t: '\t',
      name: 'Paladin One',
      duration: '12:30',
      DURATION: '750',
      damage: '147560',
      'damage-m': '0.15',
      'DAMAGE-k': '148',
      'DAMAGE-m': '0',
      'damage%': '8%',
      dps: '196.75',
      DPS: '197',
      'DPS-k': '0',
      encdps: '187.02',
      ENCDPS: '187',
      'ENCDPS-k': '0',
      hits: '721',
      crithits: '132',
      'crithit%': '18%',
      misses: '0',
      hitfailed: '0',
      swings: '721',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: 'Rage Of Halone-842',
      MAXHIT: '842',
      healed: '10356',
      'healed%': '0%',
      enchps: '13.13',
      ENCHPS: '13',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '72',
      cures: '0',
      maxheal: 'Stoneskin-947',
      MAXHEAL: '947',
      maxhealward: 'Stoneskin-947',
      MAXHEALWARD: '947',
      damagetaken: '305666',
      healstaken: '569140',
      powerdrain: '0',
      powerheal: '266',
      kills: '1',
      deaths: '1',
      threatstr: '+(0)0/-(0)28032',
      threatdelta: '-28032',
      NAME3: 'Pal',
      NAME4: 'Pala',
      NAME5: 'Palad',
      NAME6: 'Paladi',
      NAME7: 'Paladin',
      NAME8: 'Paladin',
      NAME9: 'Paladin O',
      NAME10: 'Paladin On',
      NAME11: 'Paladin One',
      NAME12: 'Paladin One',
      NAME13: 'Paladin One',
      NAME14: 'Paladin One',
      NAME15: 'Paladin One',
      Last10DPS: '0',
      Last30DPS: '0',
      Last60DPS: '28',
      Job: 'Pld',
      ParryPct: '7%',
      BlockPct: '27%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Scholar One': {
      n: '\n',
      t: '\t',
      name: 'Scholar One',
      duration: '13:21',
      DURATION: '801',
      damage: '67373',
      'damage-m': '0.07',
      'DAMAGE-k': '67',
      'DAMAGE-m': '0',
      'damage%': '3%',
      dps: '84.11',
      DPS: '84',
      'DPS-k': '0',
      encdps: '85.39',
      ENCDPS: '85',
      'ENCDPS-k': '0',
      hits: '373',
      crithits: '95',
      'crithit%': '25%',
      misses: '7',
      hitfailed: '0',
      swings: '380',
      tohit: '98.16',
      TOHIT: '98',
      maxhit: 'Energy Drain-1048',
      MAXHIT: '1048',
      healed: '836767',
      'healed%': '46%',
      enchps: '1060.54',
      ENCHPS: '1061',
      'ENCHPS-k': '1',
      critheals: '220',
      'critheal%': '23%',
      heals: '968',
      cures: '0',
      maxheal: 'Galvanize-4222',
      MAXHEAL: '4222',
      maxhealward: 'Galvanize-4222',
      MAXHEALWARD: '4222',
      damagetaken: '70693',
      healstaken: '244571',
      powerdrain: '0',
      powerheal: '12817',
      kills: '0',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Sch',
      NAME4: 'Scho',
      NAME5: 'Schol',
      NAME6: 'Schola',
      NAME7: 'Scholar',
      NAME8: 'Scholar',
      NAME9: 'Scholar O',
      NAME10: 'Scholar On',
      NAME11: 'Scholar One',
      NAME12: 'Scholar One',
      NAME13: 'Scholar One',
      NAME14: 'Scholar One',
      NAME15: 'Scholar One',
      Last10DPS: '0',
      Last30DPS: '154',
      Last60DPS: '134',
      Job: 'Sch',
      ParryPct: '0%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '42%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Limit Break': {
      n: '\n',
      t: '\t',
      name: 'Limit Break',
      duration: '03:36',
      DURATION: '216',
      damage: '34210',
      'damage-m': '0.03',
      'DAMAGE-k': '34',
      'DAMAGE-m': '0',
      'damage%': '1%',
      dps: '158.38',
      DPS: '158',
      'DPS-k': '0',
      encdps: '43.36',
      ENCDPS: '43',
      'ENCDPS-k': '0',
      hits: '1',
      crithits: '0',
      'crithit%': '0%',
      misses: '0',
      hitfailed: '0',
      swings: '1',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: 'Final Heaven-34210',
      MAXHIT: '34210',
      healed: '0',
      'healed%': '0%',
      enchps: '0.00',
      ENCHPS: '0',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '0',
      cures: '0',
      maxheal: '',
      MAXHEAL: '',
      maxhealward: '',
      MAXHEALWARD: '',
      damagetaken: '0',
      healstaken: '0',
      powerdrain: '0',
      powerheal: '0',
      kills: '0',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Lim',
      NAME4: 'Limi',
      NAME5: 'Limit',
      NAME6: 'Limit',
      NAME7: 'Limit B',
      NAME8: 'Limit Br',
      NAME9: 'Limit Bre',
      NAME10: 'Limit Brea',
      NAME11: 'Limit Break',
      NAME12: 'Limit Break',
      NAME13: 'Limit Break',
      NAME14: 'Limit Break',
      NAME15: 'Limit Break',
      Last10DPS: '0',
      Last30DPS: '0',
      Last60DPS: '0',
      Job: '',
      ParryPct: '0%',
      BlockPct: '0%',
      IncToHit: '---',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'WhiteMage One': {
      n: '\n',
      t: '\t',
      name: 'WhiteMage One',
      duration: '13:07',
      DURATION: '787',
      damage: '1980',
      'damage-m': '0.00',
      'DAMAGE-k': '2',
      'DAMAGE-m': '0',
      'damage%': '0%',
      dps: '2.52',
      DPS: '3',
      'DPS-k': '0',
      encdps: '2.51',
      ENCDPS: '3',
      'ENCDPS-k': '0',
      hits: '12',
      crithits: '0',
      'crithit%': '0%',
      misses: '1',
      hitfailed: '0',
      swings: '13',
      tohit: '92.31',
      TOHIT: '92',
      maxhit: 'Stone II-745',
      MAXHIT: '745',
      healed: '926061',
      'healed%': '51%',
      enchps: '1173.71',
      ENCHPS: '1174',
      'ENCHPS-k': '1',
      critheals: '115',
      'critheal%': '7%',
      heals: '1597',
      cures: '4',
      maxheal: 'Benediction-6974',
      MAXHEAL: '6974',
      maxhealward: 'Benediction-6974',
      MAXHEALWARD: '6974',
      damagetaken: '78963',
      healstaken: '127280',
      powerdrain: '0',
      powerheal: '580',
      kills: '1',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Whi',
      NAME4: 'Whit',
      NAME5: 'White',
      NAME6: 'WhiteM',
      NAME7: 'WhiteMa',
      NAME8: 'WhiteMag',
      NAME9: 'WhiteMage',
      NAME10: 'WhiteMage',
      NAME11: 'WhiteMage O',
      NAME12: 'WhiteMage On',
      NAME13: 'WhiteMage One',
      NAME14: 'WhiteMage One',
      NAME15: 'WhiteMage One',
      Last10DPS: '0',
      Last30DPS: '56',
      Last60DPS: '31',
      Job: 'Whm',
      ParryPct: '0%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '42%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
  },
  isActive: true,
};
var ActFakeData4 = {
  Encounter: {
    n: '\n',
    t: '\t',
    title: 'An enemy',
    duration: '13:09',
    DURATION: '789',
    damage: '1840349',
    'damage-m': '1.84',
    'DAMAGE-k': '1840',
    'DAMAGE-m': '2',
    dps: '2332.51',
    DPS: '2333',
    'DPS-k': '2',
    encdps: '2332.51',
    ENCDPS: '2333',
    'ENCDPS-k': '2',
    hits: '4942',
    crithits: '1206',
    'crithit%': '0%',
    misses: '11',
    hitfailed: '0',
    swings: '4953',
    tohit: '98.90',
    TOHIT: '99',
    maxhit: 'Limit Break-Final Heaven-34210',
    MAXHIT: 'Limit Break-34210',
    healed: '1810233',
    enchps: '2294.34',
    ENCHPS: '2294',
    'ENCHPS-k': '2',
    critheals: '1206',
    'critheal%': '0%',
    heals: '2771',
    cures: '4',
    maxheal: 'White Mage One-Benediction-6974',
    MAXHEAL: 'White Mage One-6974',
    maxhealward: 'White Mage One-Benediction-6974',
    MAXHEALWARD: 'White Mage One-6974',
    damagetaken: '1052500',
    healstaken: '1812323',
    powerdrain: '0',
    powerheal: '18483',
    kills: '10',
    deaths: '4',
    CurrentZoneName: 'An instance',
    Last10DPS: '2095',
    Last30DPS: '1922',
    Last60DPS: '2347',
  },
  Combatant: {
    'Bard One': {
      n: '\n',
      t: '\t',
      name: 'YOU',
      duration: '13:09',
      DURATION: '789',
      damage: '350064',
      'damage-m': '0.35',
      'DAMAGE-k': '350',
      'DAMAGE-m': '0',
      'damage%': '19%',
      dps: '443.68',
      DPS: '444',
      'DPS-k': '0',
      encdps: '443.68',
      ENCDPS: '444',
      'ENCDPS-k': '0',
      hits: '1240',
      crithits: '475',
      'crithit%': '38%',
      misses: '0',
      hitfailed: '0',
      swings: '1240',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: 'Heavy Shot-1016',
      MAXHIT: '1016',
      healed: '2798',
      'healed%': '0%',
      enchps: '3.55',
      ENCHPS: '4',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '3',
      cures: '0',
      maxheal: 'Second Wind-1005',
      MAXHEAL: '1005',
      maxhealward: 'Second Wind-1005',
      MAXHEALWARD: '1005',
      damagetaken: '77145',
      healstaken: '122216',
      powerdrain: '0',
      powerheal: '0',
      kills: '1',
      deaths: '1',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'YOU',
      NAME4: 'YOU',
      NAME5: 'YOU',
      NAME6: 'YOU',
      NAME7: 'YOU',
      NAME8: 'YOU',
      NAME9: 'YOU',
      NAME10: 'YOU',
      NAME11: 'YOU',
      NAME12: 'YOU',
      NAME13: 'YOU',
      NAME14: 'YOU',
      NAME15: 'YOU',
      Last10DPS: '0',
      Last30DPS: '293',
      Last60DPS: '354',
      Job: 'Brd',
      ParryPct: '50%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '34%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Dragoon One': {
      n: '\n',
      t: '\t',
      name: 'Dragoon One',
      duration: '13:06',
      DURATION: '786',
      damage: '331961',
      'damage-m': '0.33',
      'DAMAGE-k': '332',
      'DAMAGE-m': '0',
      'damage%': '18%',
      dps: '422.34',
      DPS: '422',
      'DPS-k': '0',
      encdps: '420.74',
      ENCDPS: '421',
      'ENCDPS-k': '0',
      hits: '830',
      crithits: '141',
      'crithit%': '17%',
      misses: '1',
      hitfailed: '0',
      swings: '831',
      tohit: '99.88',
      TOHIT: '100',
      maxhit: 'Full Thrust-2488',
      MAXHIT: '2488',
      healed: '11656',
      'healed%': '0%',
      enchps: '14.77',
      ENCHPS: '15',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '26',
      cures: '0',
      maxheal: 'Second Wind-1108',
      MAXHEAL: '1108',
      maxhealward: 'Second Wind-1108',
      MAXHEALWARD: '1108',
      damagetaken: '90082',
      healstaken: '155129',
      powerdrain: '0',
      powerheal: '0',
      kills: '2',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Dra',
      NAME4: 'Drag',
      NAME5: 'Drago',
      NAME6: 'Dragoo',
      NAME7: 'Dragoon',
      NAME8: 'Dragoon',
      NAME9: 'Dragoon O',
      NAME10: 'Dragoon On',
      NAME11: 'Dragoon One',
      NAME12: 'Dragoon One',
      NAME13: 'Dragoon One',
      NAME14: 'Dragoon One',
      NAME15: 'Dragoon One',
      Last10DPS: '0',
      Last30DPS: '168',
      Last60DPS: '353',
      Job: 'Drg',
      ParryPct: '55%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Paladin One': {
      n: '\n',
      t: '\t',
      name: 'Paladin One',
      duration: '12:30',
      DURATION: '750',
      damage: '147560',
      'damage-m': '0.15',
      'DAMAGE-k': '148',
      'DAMAGE-m': '0',
      'damage%': '8%',
      dps: '196.75',
      DPS: '197',
      'DPS-k': '0',
      encdps: '187.02',
      ENCDPS: '187',
      'ENCDPS-k': '0',
      hits: '721',
      crithits: '132',
      'crithit%': '18%',
      misses: '0',
      hitfailed: '0',
      swings: '721',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: 'Rage Of Halone-842',
      MAXHIT: '842',
      healed: '10356',
      'healed%': '0%',
      enchps: '13.13',
      ENCHPS: '13',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '72',
      cures: '0',
      maxheal: 'Stoneskin-947',
      MAXHEAL: '947',
      maxhealward: 'Stoneskin-947',
      MAXHEALWARD: '947',
      damagetaken: '305666',
      healstaken: '569140',
      powerdrain: '0',
      powerheal: '266',
      kills: '1',
      deaths: '1',
      threatstr: '+(0)0/-(0)28032',
      threatdelta: '-28032',
      NAME3: 'Pal',
      NAME4: 'Pala',
      NAME5: 'Palad',
      NAME6: 'Paladi',
      NAME7: 'Paladin',
      NAME8: 'Paladin',
      NAME9: 'Paladin O',
      NAME10: 'Paladin On',
      NAME11: 'Paladin One',
      NAME12: 'Paladin One',
      NAME13: 'Paladin One',
      NAME14: 'Paladin One',
      NAME15: 'Paladin One',
      Last10DPS: '0',
      Last30DPS: '0',
      Last60DPS: '28',
      Job: 'Pld',
      ParryPct: '7%',
      BlockPct: '27%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Scholar One': {
      n: '\n',
      t: '\t',
      name: 'Scholar One',
      duration: '13:21',
      DURATION: '801',
      damage: '67373',
      'damage-m': '0.07',
      'DAMAGE-k': '67',
      'DAMAGE-m': '0',
      'damage%': '3%',
      dps: '84.11',
      DPS: '84',
      'DPS-k': '0',
      encdps: '85.39',
      ENCDPS: '85',
      'ENCDPS-k': '0',
      hits: '373',
      crithits: '95',
      'crithit%': '25%',
      misses: '7',
      hitfailed: '0',
      swings: '380',
      tohit: '98.16',
      TOHIT: '98',
      maxhit: 'Energy Drain-1048',
      MAXHIT: '1048',
      healed: '836767',
      'healed%': '46%',
      enchps: '1060.54',
      ENCHPS: '1061',
      'ENCHPS-k': '1',
      critheals: '220',
      'critheal%': '23%',
      heals: '968',
      cures: '0',
      maxheal: 'Galvanize-4222',
      MAXHEAL: '4222',
      maxhealward: 'Galvanize-4222',
      MAXHEALWARD: '4222',
      damagetaken: '70693',
      healstaken: '244571',
      powerdrain: '0',
      powerheal: '12817',
      kills: '0',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Sch',
      NAME4: 'Scho',
      NAME5: 'Schol',
      NAME6: 'Schola',
      NAME7: 'Scholar',
      NAME8: 'Scholar',
      NAME9: 'Scholar O',
      NAME10: 'Scholar On',
      NAME11: 'Scholar One',
      NAME12: 'Scholar One',
      NAME13: 'Scholar One',
      NAME14: 'Scholar One',
      NAME15: 'Scholar One',
      Last10DPS: '0',
      Last30DPS: '154',
      Last60DPS: '134',
      Job: 'Sch',
      ParryPct: '0%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '42%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Limit Break': {
      n: '\n',
      t: '\t',
      name: 'Limit Break',
      duration: '03:36',
      DURATION: '216',
      damage: '34210',
      'damage-m': '0.03',
      'DAMAGE-k': '34',
      'DAMAGE-m': '0',
      'damage%': '1%',
      dps: '158.38',
      DPS: '158',
      'DPS-k': '0',
      encdps: '43.36',
      ENCDPS: '43',
      'ENCDPS-k': '0',
      hits: '1',
      crithits: '0',
      'crithit%': '0%',
      misses: '0',
      hitfailed: '0',
      swings: '1',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: 'Final Heaven-34210',
      MAXHIT: '34210',
      healed: '0',
      'healed%': '0%',
      enchps: '0.00',
      ENCHPS: '0',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '0',
      cures: '0',
      maxheal: '',
      MAXHEAL: '',
      maxhealward: '',
      MAXHEALWARD: '',
      damagetaken: '0',
      healstaken: '0',
      powerdrain: '0',
      powerheal: '0',
      kills: '0',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Lim',
      NAME4: 'Limi',
      NAME5: 'Limit',
      NAME6: 'Limit',
      NAME7: 'Limit B',
      NAME8: 'Limit Br',
      NAME9: 'Limit Bre',
      NAME10: 'Limit Brea',
      NAME11: 'Limit Break',
      NAME12: 'Limit Break',
      NAME13: 'Limit Break',
      NAME14: 'Limit Break',
      NAME15: 'Limit Break',
      Last10DPS: '0',
      Last30DPS: '0',
      Last60DPS: '0',
      Job: '',
      ParryPct: '0%',
      BlockPct: '0%',
      IncToHit: '---',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
    'Boco (Dragoon One)': {
      n: '\n',
      t: '\t',
      name: 'Boco (Dragoon One)',
      duration: '00:18',
      DURATION: '18',
      damage: '5834',
      'damage-m': '0.01',
      'DAMAGE-k': '6',
      'DAMAGE-m': '0',
      'damage%': '33%',
      dps: '324.11',
      DPS: '324',
      'DPS-k': '0',
      encdps: '324.11',
      ENCDPS: '324',
      'ENCDPS-k': '0',
      hits: '9',
      crithits: '1',
      'crithit%': '11%',
      misses: '0',
      hitfailed: '0',
      swings: '9',
      tohit: '100.00',
      TOHIT: '100',
      maxhit: 'Attack-859',
      MAXHIT: '859',
      healed: '260',
      'healed%': '100%',
      enchps: '14.44',
      ENCHPS: '14',
      'ENCHPS-k': '0',
      critheals: '0',
      'critheal%': '0%',
      heals: '2',
      cures: '0',
      maxheal: 'Choco Regen (*)-130',
      MAXHEAL: '130',
      maxhealward: 'Choco Regen (*)-130',
      MAXHEALWARD: '130',
      damagetaken: '213',
      healstaken: '505',
      powerdrain: '0',
      powerheal: '0',
      kills: '0',
      deaths: '0',
      threatstr: '+(0)0/-(0)0',
      threatdelta: '0',
      NAME3: 'Boc',
      NAME4: 'Boco',
      NAME5: 'Boco',
      NAME6: 'Boco (',
      NAME7: 'Boco (D',
      NAME8: 'Boco (Dr',
      NAME9: 'Boco (Dra',
      NAME10: 'Boco (Drag',
      NAME11: 'Boco (Drago',
      NAME12: 'Boco (Dragoo',
      NAME13: 'Boco (Dragoon',
      NAME14: 'Boco (Dragoon',
      NAME15: 'Boco (Dragoon O)',
      Last10DPS: '176',
      Last30DPS: '324',
      Last60DPS: '324',
      Job: '',
      ParryPct: '0%',
      BlockPct: '0%',
      IncToHit: '100.00',
      OverHealPct: '0%',
      DirectHitPct: '0%',
      DirectHitCount: '0',
      CritDirectHitCount: '0',
    },
  },
  isActive: false,
};

setTimeout(function() {
  var event = new CustomEvent('onOverlayDataUpdate', { detail: ActData });
  document.dispatchEvent(event);
}, 500);

setInterval(() => {
  const myDate = new Date();
  const duration = myDate.getMinutes() + ':' + myDate.getSeconds();

  let allDps = 0,
    allEncdps = 0;

  const { Combatant, Encounter } = ActData;

  _.forEach(Combatant, item => {
    const dps = parseInt((Math.random() * 1000 + 100).toFixed(2));
    const encdps = parseInt((dps - Math.random() * 100).toFixed(2));

    item.dps = dps;
    item.DPS = Math.round(dps);
    allDps = allDps + dps;

    item.encdps = encdps;
    item.ENCDPS = Math.round(encdps);
    allEncdps = allEncdps + encdps;
  });

  Encounter.duration = duration;
  Encounter.dps = allDps;
  Encounter.DPS = Math.round(allDps);
  Encounter.encdps = allEncdps;
  Encounter.ENCDPS = Math.round(allEncdps);

  _.forEach(Combatant, item => {
    item['damage%'] = parseInt(item.dps / Encounter.dps * 100);
  });

  const event = new CustomEvent('onOverlayDataUpdate', { detail: ActData });
  document.dispatchEvent(event);
}, 10000);
